# Generated by Django 4.1.2 on 2023-02-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pp',
            field=models.ImageField(default=None, upload_to='profile'),
        ),
    ]
